config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  root 'articles#index'
  resources :articles do
    resources :comments
    member do
      put "like", to: "articles#upvote"
      put "dislike", to: "articles#downvote"
    end
  end
  get 'tags/:tag', to: 'articles#index', as: :tag

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_votable
  acts_as_taggable
  has_attached_file :image, styles: { large: "900x300", medium: "330x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_many :comments
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :articles
  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :check_is_admin, only: [:new, :edit, :destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag] && current_user != "admin"
      @articles = Article.order(created_at: :desc).page(params[:page]).per(4).tagged_with(params[:tag])
    else
      if user_signed_in? && current_user.role == "admin"
        @q = Article.ransack(params[:q])
        @articles = @q.result.order(created_at: :desc)
      else
        @articles = Article.order(created_at: :desc).page(params[:page]).per(4)
      end
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to articles_url, notice: 'Article was successfully update.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check_is_admin
   if current_user.role != "admin"
      redirect_to articles_url
   end
  end

  def upvote
    @article.upvote_by current_user
    redirect_to :back
  end

  def downvote
   @article.downvote_by current_user
   redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :published, :image, :tag_list)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @article, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:article_id, :content, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article, html: { multipart: true }) do |f| %>
  <%= f.error_notification %>
    <div class="row">
      <div class="col-md-10 col-md-offset-1 text-center">
        <div class="form-inputs">
          <%= f.input :title, label: false, placeholder: 'Title' %>
          <%= f.input :content, as: :text, input_html: {class: "vresize"}, label: false, placeholder: 'Content' %>
          <div class="row">
            <div class="col-md-4">
              <%= f.file_field :image, class: "btn btn-primary position_file_fiel" %>
            </div>
            <div class="col-md-4">
              <%= image_tag @article.image.url(:medium) %>
            </div>
          </div>
          <div class="row color_white">
            <div class="col-md-4">
              <%= f.input :tag_list, hint: t('separate_each_tag_with_a_comma') %>
            </div>
            <div class="col-md-4">
              <%= f.input :published, label: false, input_html: {class: 'switch', 'data-on-text': 'publier', 'data-off-text': 'brouillon'} %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
        <div class="form-actions">
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
      </div>
    </div>
<% end %>

<script type="text/javascript">
  $(function() {
    $("#article_published").bootstrapSwitch();
});
</script>

app/views/articles/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="text-center color_white ">Editing Article</h1>
  </div>
</div>
<%= render 'form' %>
<div class="row">
  <div class="col-md-6 col-md-offset-1">
    <%= link_to 'Show', @article, class: "btn btn-default" %> |
    <%= link_to 'Back', articles_path, class: "btn btn-default" %> | <%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
  </div>
</div>
<script type="text/javascript">
  switch_button();
</script>

app/views/articles/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <% if user_signed_in? && current_user.role == "admin" %>
      <h1 class="text-center">Mes articles</h1>
    <% end %>
  </div>
</div>
<% if user_signed_in? && current_user.role == 'admin' %>
  <div class="row">
    <div class="col-md-2">
      <fieldset class="filter-panel">
        <%= search_form_for @q do |f| %>
          <div class="form-group dictionary">
            <%= f.search_field :title_cont, placeholder: t('.title') %>
          </div>
          <div class="form-group dictionary">
            <%= f.search_field :content_cont, placeholder: t('.content') %>
          </div>
          <div class="form-group dictionary">
            <%= f.check_box :published_eq, class: 'switch', 'data-on-text': 'publier', 'data-off-text': 'brouillon' %>
          </div>
          <%= f.button t(:submit), class: 'btn btn-primary btn-block' %>
        <% end %>
        <br>
        <%= link_to t('reset_search'), url_for(action: 'index'), class: 'btn btn-default btn-block' %>
      </fieldset>
    </div>
    <div class="col-md-8 col-md-offset-1">
      <table border class="table">
        <thead>
          <tr>
            <th class="info"><%= sort_link(@q, :title, default_order: :asc) %></th>
            <th class="info"><%= sort_link(@q, :published, default_order: :asc) %></th>
            <th class="info">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @articles.each do |article| %>
          <tr>
            <td class="info"><%= link_to article.title, edit_article_path(article)%></td>
            <td class="info"><%= t article.published %></td>
            <td class="info"><%= link_to edit_article_path(article) do %>
                  <span class="glyphicon glyphicon-pencil"></span>
                <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-1">
      <%= link_to url_for(action: :new) do %>
        <span class="btn btn-sm btn-default glyphicon glyphicon-plus"></span>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <p><%= t('theme') %>:
          <%= link_to t('all'), root_path %>
          <% tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| %>
            <%= link_to tag.name, tag_path(tag.name), class: css_class %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <% @articles.each do |article| %>
      <% if article.published %>
        <div class="col-md-3 ">
          <h2 class="text-center well"><%= link_to article.title, article %></h2>
          <hr>
          <%= image_tag article.image.url %>
          <hr>
          <p class="well"><span class="glyphicon glyphicon-time"></span>Posté le:<%= article.created_at.strftime("%d/%m/20%y") %><br><%= truncate(article.content, length: 200) %></p>
          <%= link_to t('.more'), article, class: "btn btn-primary" %>
          <hr>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= paginate @articles %>
<% end %>

<script type="text/javascript">
  $(function() {
    $("#q_published_eq").bootstrapSwitch();
});
</script>

app/views/articles/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="text-center">New Article</h1>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Back', articles_path, class: "btn btn-primary" %>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h1 class="text-center color_white"><%= @article.title %></h1>
  </div>
</div>
<div class="row">
  <div class="col-md-3">
    <%= image_tag @article.image.url(:medium) %>
  </div>
  <div class="col-md-3">
    <p class="color_white"><%= @article.content %></p>
  </div>
</div>
<% if user_signed_in? %>
  <div class="row">
    <div class="col-md-12 text-center">
      <p class="color_white">
        <%= link_to like_article_path(@article), method: :put, class: "btn btn-primary" do %>
          <span class="glyphicon glyphicon-thumbs-up"></span>
        <% end %>
        <%= @article.get_upvotes.size %>
        <%= link_to dislike_article_path(@article), method: :put, class: "btn btn-primary" do %>
          <span class="glyphicon glyphicon-thumbs-down "></span>
        <% end %>
        <%= @article.get_downvotes.size %>
      </p>
    </div>
  </div>
<% end %>
<div class=" row text-center">
  <div class="col-md-12">
    <h2 class="comments_title well"><%= @article.comments.count %> Commentaires</h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div id="comments">
      <%= render :partial => @article.comments %>
    </div>
  </div>
</div>
<% if user_signed_in? && current_user.role != 'admin'%>
  <%= simple_form_for [@article, Comment.new]  do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= f.text_area :content, class: "form-control" %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-md-2">
        <%= f.submit "Add Comment", class: "btn btn-primary" %>
      </div>
      <div class="col-md-2">
        <%= link_to 'Back', articles_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
<% else %>
  <div class="row">
    <div class="col-md-4">
      <p class="color_white">Connectez vous pour laisser un commentaire.</p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-2">
       <%= link_to 'Back', articles_path, class: "btn btn-primary" %>
       <% if user_signed_in? && current_user.role == "admin" %>
          <%= link_to 'Edit', edit_article_path(@article) %> |
        <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
  <div class="comments_wrapper clearfix well">
    <div class="pull-left">
      <p class="lead"><%= comment.content %></p>
      <p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %></strong> par <%= comment.user.email %></small></p>
    </div>

    <div class="btn-group pull-right">
      <% if comment.user == current_user %>
        <%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= simple_form_for(@comment) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.association :article %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Article</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.article %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimplonBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Simplon Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar" aria-controls="exCollapsingNavbar" aria-expanded="false" aria-label="Toggle navigation">
            &#9776;
          </button>
          <div class="collapse" id="exCollapsingNavbar">
            <div class="bg-inverse p-a-1">
              <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <% if current_user.role == "admin" %>
                        <li><%= link_to 'Account', edit_user_registration_path %></li>
                        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                      <% else %>
                        <li><%= link_to 'Account', edit_user_registration_path %></li>
                        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                      <% end %>
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to 'Sign up', new_user_registration_path %></li>
                  <li><%= link_to 'Sign in', new_user_session_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administration <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <% if current_user.role == "admin" %>
                    <li><%= link_to 'Account', edit_user_registration_path %></li>
                    <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                  <% else %>
                    <li><%= link_to 'Account', edit_user_registration_path %></li>
                    <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
                  <% end %>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <li><%= link_to 'Sign in', new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <p class="notice color_white"><%= notice %></p>
    <p class="alert color_white"><%= alert %></p>
<%= yield %>
  </div>
  <br>
</body>
</html>